# NumPy (Numerical Python)

**NumPy** is a fundamental library for numerical computing in Python, created in **2005**.

Key features:
- **ndarray**: N-dimensional array object — fast, memory-efficient container for large datasets
- **Vectorization**: Operations on entire arrays without writing loops (much faster than Python lists)
- **Broadcasting**: Rules for applying operations on arrays of different shapes

In [1]:
import numpy as np

In [2]:
lst = [12, 15, 7, 20, 18]   # Create a Python list
a = np.array(lst) # Convert the list to a NumPy array
print(a)

[12 15  7 20 18]


In [4]:
# type() shows the data type of the variable
print(type(a))

<class 'numpy.ndarray'>


In [5]:
# ndim: number of dimensions, shape: size of each dimension, size: total elements
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size:", a.size)

ndim: 1
shape: (5,)
size: 5


In [6]:
# Indexing: access elements by position (negative index counts from end)
print("a[-1]:", a[-1])    # last element → 18
print("a[0]:", a[0])      # first element → 12
print("a[1:4]:", a[1:4])  # slice from index 1 to 3

a[-1]: 18
a[0]: 12
a[1:4]: [15  7 20]


## 2D Arrays (Matrices)

A **2D array** is created by passing a list of lists to `np.array()`. Each inner list becomes a **row** in the matrix.

- `ndim` → number of dimensions (2 for a matrix)
- `shape` → returns `(rows, columns)`
- Indexing: `b[row]` returns a row, `b[row][col]` returns a single element

In [7]:
lst = [[12, 15, 7, 20, 18],[14, 16, 15, 13, 3]]
b = np.array(lst)

In [8]:
print(b)

[[12 15  7 20 18]
 [14 16 15 13  3]]


In [137]:
b.ndim  # This will output: 2 number of dimensions
print(b.ndim)

2


In [9]:
b.shape     # This will output: (2, 5) number of rows and columns
print(b.shape)  

(2, 5)


In [10]:
d = np.array([[1,2,3],
              [4,5,6]])
print(d.shape)
print(d.ndim)

(2, 3)
2


In [11]:
print(b[1])    # This will output: [4 5 6]
print(b[0,2])  # This will output: 3
print(b[:,1])  # This will output: [2 5]

[14 16 15 13  3]
7
[15 16]


In [12]:
print(b[1][2])  # Use the last valid index (2) since the second row has 3 elements.

15


In [ ]:
# Negative index: -1 means last element of that row
print(b[1][-1])

## Data Type, Size & Memory

- `dtype` → the data type of elements (e.g., `int64`, `float32`)
- `size` → total number of elements in the array
- `nbytes` → total memory used in bytes (`size × bytes_per_element`)
  - `int64` = 8 bytes per element, so an array of 5 elements uses 5 × 8 = **40 bytes**

In [ ]:
# dtype: data type of all elements in the array
print("a.dtype:", a.dtype)

In [ ]:
print("b.dtype:", b.dtype)

In [147]:
a       # This will output: array([12, 15,  7, 20, 18])
print(a)    

[12 15  7 20 18]


In [148]:
print(a.size)  # This will output: 5

5


In [149]:
print(b.size)  # This will output: 10

6


In [ ]:
# nbytes: total memory in bytes = size × bytes_per_element
print("a.nbytes:", a.nbytes)  # 5 elements × 8 bytes (int64) = 40

In [ ]:
# Each int64 element uses 8 bytes
print("a[0].nbytes:", a[0].nbytes)

In [ ]:
print("b.nbytes:", b.nbytes)

In [ ]:
print("b[0][0].nbytes:", b[0][0].nbytes)

## Array Creation Functions

NumPy provides several convenient functions to create arrays:

| Function | Description |
|---|---|
| `np.zeros(shape)` | Array filled with **0.0** |
| `np.ones(shape)` | Array filled with **1.0** |
| `np.eye(n)` | **Identity matrix** (1s on diagonal, 0s elsewhere) |
| `np.arange(start, stop, step)` | Evenly spaced values (like `range()` but returns an array) |
| `np.linspace(start, stop, num)` | `num` evenly spaced values between start and stop (inclusive) |

In [157]:
np.zeros(5) # This will create a 1D array of zeros with 5 elements.
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [ ]:
# 2D array of zeros with shape (5, 2)
print(np.zeros((5, 2)))

In [ ]:
# ones(): array filled with 1.0
w = np.ones((5, 2))
print(w)

In [ ]:
# eye(): identity matrix (1s on diagonal)
print(np.eye(4))

In [160]:
np.arange(0, 10, 2)
print(np.arange(0, 10, 2).reshape(5,1))

[[0]
 [2]
 [4]
 [6]
 [8]]


In [162]:
print(np.arange(0, 10, 3))

[0 3 6 9]


In [164]:
print(np.arange(20, 40, 5))

[20 25 30 35]


In [165]:
print(np.linspace(0, 1, 5))  # This will create an array of 5 evenly spaced numbers between 0 and 1.

[0.   0.25 0.5  0.75 1.  ]


In [167]:
print(np.linspace(10, 20, 4))  # This will create an array of 4 evenly spaced numbers between 10 and 20.

[10.         13.33333333 16.66666667 20.        ]


## Specifying Data Type (`dtype`)

You can set the data type when creating an array using the `dtype` parameter.

For example, `dtype=np.float32` stores each element as a **32-bit float** (4 bytes) instead of the default **64-bit int** (8 bytes). This **saves memory** — useful for large datasets.

In [169]:
lst = [12, 15, 7, 20, 18]
a = np.array(lst, dtype=np.float32)
print(a)

[12. 15.  7. 20. 18.]


In [170]:
a.nbytes   # 5 * 4                     32 / 8 = 4
print(a.nbytes)

20


## Slicing 2D Arrays

Slicing syntax: `array[row_slice, col_slice]`

- `b[0, :]` → all columns of row 0
- `b[0, 1:]` → row 0, from column 1 to end
- `b[0, 1:4]` → row 0, columns 1 to 3
- `b[:, 1:3]` → all rows, columns 1 and 2
- `b[::-1]` → reverse the order of rows

In [171]:
lst = [[12, 15, 7, 20, 18],[14, 16, 15, 13, 3],[4, 6, 5, 99, 23],[7, 8, 12, 11, 3]]
b = np.array(lst) # Convert the list to a NumPy array
print(b)

[[12 15  7 20 18]
 [14 16 15 13  3]
 [ 4  6  5 99 23]
 [ 7  8 12 11  3]]


In [172]:
print(b[0,:])

[12 15  7 20 18]


In [173]:
print(b[0,1:])

[15  7 20 18]


In [174]:
print(b[0,1:4])

[15  7 20]


In [176]:
print(b)

[[12 15  7 20 18]
 [14 16 15 13  3]
 [ 4  6  5 99 23]
 [ 7  8 12 11  3]]


In [ ]:
# All rows, columns 1 and 2
print(b[:, 1:3])

In [ ]:
print(b)

In [ ]:
# [::-1] reverses the order of rows
c = b[::-1]
print(c)

## Boolean Masking (Filtering)

A **boolean mask** is created by applying a condition to an array. It returns a `True`/`False` array of the same shape.

Using the mask as an index returns only the elements where the condition is `True`:
- `b[b < 10]` → all elements less than 10
- `b[(b >= 12) & (b <= 15)]` → elements between 12 and 15 (use `&` for AND, `|` for OR)

In [ ]:
print(b)

In [ ]:
# Boolean mask: True where condition is met
print(b < 10)

In [178]:
print(b[b<10])

[7 3 4 6 5 7 8 3]


In [179]:
print(b[(b >= 12) & ( b <= 15)])

[12 15 14 15 13 12]


## Fancy Indexing

Selecting elements using a **list or array of indices** (not slices).

- Select specific **rows**: `b[[0, 2]]` → rows 0 and 2
- Select specific **elements**: `b[[r1, r2], [c1, c2]]` → elements at (r1,c1) and (r2,c2)

This is different from basic slicing — fancy indexing always returns a **copy**, not a view.

In [ ]:
b = np.array([[12, 15, 7, 20, 18],
              [14, 16, 15, 13, 3],
              [4, 6, 5, 99, 23],
              [7, 8, 12, 11, 3]])

# Select rows 0 and 2 using a list of indices
print(b[[0, 2]])

In [180]:
# Select specific elements: b[0,1], b[1,3], b[2,4]
print(b[[0, 1, 2], [1, 3, 4]])

[15 13 23]


## 3D Arrays

A **3D array** has 3 dimensions: `(depth, rows, columns)`. Think of it as a list of 2D matrices.

- `ndim` = 3
- `shape` = `(depth, rows, cols)`
- Indexing: `arr[depth, row, col]`

In [ ]:
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print("Shape:", arr_3d.shape)   # (2, 2, 3) → 2 matrices, each 2×3
print("ndim:", arr_3d.ndim)
print(arr_3d)

In [48]:
# Indexing: arr_3d[depth, row, col]
print("First matrix:\n", arr_3d[0])
print("Element at depth=0, row=1, col=2:", arr_3d[0, 1, 2])  # → 6

First matrix:
 [[1 2 3]
 [4 5 6]]
Element at depth=0, row=1, col=2: 6


## Assigning Values

You can assign values to slices or specific rows of an array:
- `b[:2, :] = 0` → set the first 2 rows to 0
- `b[[0, 2]] = 100` → set rows 0 and 2 to 100 (fancy indexing)

**Note:** This modifies the array **in place**.

In [ ]:
print(b)

### Understanding `b[:2, :]`

This is **2D slicing** with two parts separated by a comma: `array[row_slice, col_slice]`

| Part | Meaning |
|---|---|
| `:2` | **Rows**: from start up to (not including) index 2 → rows **0** and **1** |
| `:` | **Columns**: all columns (no filtering) |

```
b = [[12, 15,  7, 20, 18],   ← row 0  ✅ selected
     [14, 16, 15, 13,  3],   ← row 1  ✅ selected
     [ 4,  6,  5, 99, 23],   ← row 2  ✗
     [ 7,  8, 12, 11,  3]]   ← row 3  ✗

b[:2, :] → [[12, 15,  7, 20, 18],
            [14, 16, 15, 13,  3]]
```

In [181]:
b[:2, :] = 0 # Set the first two rows to zero
print(b)

[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 4  6  5 99 23]
 [ 7  8 12 11  3]]


In [182]:
b[[0,2]] = 100 # Set rows 0 and 2 to 100
print(b)

[[100 100 100 100 100]
 [  0   0   0   0   0]
 [100 100 100 100 100]
 [  7   8  12  11   3]]


## Element-wise Operations

NumPy performs arithmetic **element by element** on arrays of the same shape:
- `x + y` → adds corresponding elements
- `x * y` → multiplies corresponding elements
- `x / y` → divides corresponding elements
- `x * 10` → **broadcasting** — multiplies every element by 10

This is called **vectorization** and is much faster than looping through elements manually.

In [52]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [ ]:
# Element-wise addition: [1+4, 2+5, 3+6]
z = x + y
print("x + y =", z)

In [ ]:
# Element-wise multiplication: [1*4, 2*5, 3*6]
print("x * y =", x * y)

In [ ]:
# Element-wise division: [1/4, 2/5, 3/6]
print("x / y =", x / y)

In [ ]:
# Broadcasting: scalar 10 is applied to every element
print("x * 10 =", x * 10)

In [ ]:
print("x =", x)

In [ ]:
# sqrt: square root of each element
print("sqrt(x) =", np.sqrt(x))

### Universal Math Functions (ufuncs)

NumPy provides **vectorized** math functions that operate on every element:
- `np.sqrt(x)` → square root of each element
- `np.log(x)` → natural logarithm (ln) of each element
- `np.exp(x)` → e raised to the power of each element (e^x)

In [ ]:
# log: natural logarithm (ln) of each element
print("log(x) =", np.log(x))

In [ ]:
# exp: e^x for each element
print("exp(x) =", np.exp(x))

In [ ]:
print("x =", x)

In [ ]:
# sum: add all elements together
print("sum(x) =", np.sum(x))

### Aggregate Functions

These reduce an array to a single value:
- `np.sum(x)` → sum of all elements
- `np.min(x)` / `np.max(x)` → minimum / maximum
- `np.mean(x)` → average (mean)
- `np.std(x)` → standard deviation

In [ ]:
# min: smallest element
print("min(x) =", np.min(x))

In [ ]:
# max: largest element
print("max(x) =", np.max(x))

In [ ]:
# mean: average of all elements
print("mean(x) =", np.mean(x))

In [ ]:
# std: standard deviation (how spread out the values are)
print("std(x) =", np.std(x))

In [67]:
lst = [[12, 15, 7, 20, 18],[14, 16, 15, 13, 3],[4, 6, 5, 99, 23],[7, 8, 12, 11, 3]]
m = np.array(lst)

In [ ]:
print(m)

In [ ]:
# min of entire matrix (all elements)
print("min(m) =", np.min(m))

In [ ]:
# min of first row only
print("min(m[0]) =", np.min(m[0]))

In [ ]:
# axis=1: min of each row
print("min(m, axis=1) =", np.min(m, axis=1))

### Axis Parameter

For 2D arrays, you can apply aggregate functions along a specific **axis**:
- `axis=0` → operate along **columns** (collapse rows)
- `axis=1` → operate along **rows** (collapse columns)
- No axis → operates on **all** elements

`np.argmin()` / `np.argmax()` return the **index** of the min/max value instead of the value itself.

In [ ]:
# axis=0: min of each column
print("min(m, axis=0) =", np.min(m, axis=0))

In [ ]:
# axis=0: sum of each column
print("sum(m, axis=0) =", np.sum(m, axis=0))

In [ ]:
print(m)

In [ ]:
# argmin: index of the minimum value (flattened)
print("argmin(m) =", np.argmin(m))

In [ ]:
# argmin axis=0: row index of min value in each column
print("argmin(m, axis=0) =", np.argmin(m, axis=0))

## Padding Arrays (`np.pad`)

`np.pad(array, (before, after))` adds zeros to the beginning or end of an array.

This is useful when you need to **add arrays of different lengths** — pad the shorter one with zeros first so both arrays have the same size.

In [77]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([11, 15, 16])

In [ ]:
# Pad shorter array with zeros, then add
result = np.pad(x, (0, max(0, len(y)-len(x)))) + np.pad(y, (0, max(0, len(x)-len(y))))
print(result)

## Reshape

`reshape(rows, cols)` changes the **shape** of an array without changing its data.

- The total number of elements must stay the same (e.g., 12 elements → 3×4, 4×3, 6×2, etc.)
- Use `-1` to let NumPy **calculate** one dimension automatically: `reshape(3, -1)` → NumPy figures out the columns

In [79]:
f = np.arange(12)

In [ ]:
print(f)

In [ ]:
# reshape 12 elements into 3 rows × 4 columns
n = f.reshape(3, 4)
print(n)

In [ ]:
# reshape 12 elements into 4 rows × 3 columns
print(f.reshape(4, 3))

In [ ]:
# reshape into 6 rows × 2 columns
t = f.reshape(6, 2)
print(t)

In [ ]:
# -1 means NumPy calculates that dimension automatically: 15/3 = 5 columns
p = np.arange(15)
print(p.reshape(3, -1))

## Ravel (Flatten: 2D → 1D)

`ravel()` flattens a multi-dimensional array into a **1D array**.

It returns a **view** (not a copy), so it's memory efficient. The elements are read **row by row** (C-order by default).

In [ ]:
# ravel: flatten 2D array to 1D (row by row)
print(t.ravel())

In [ ]:
# t is unchanged (ravel returns a view)
print(t)

## Transposing

`.T` swaps **rows and columns** of a 2D array (transpose).

A matrix with shape `(3, 5)` becomes `(5, 3)` after transposing. This is essential in **linear algebra** and matrix operations.

In [ ]:
p = np.arange(15)
r = p.reshape(3, 5)
print(r)

In [ ]:
# .T transposes: rows become columns and vice versa (3,5) → (5,3)
print(r.T)

## Concatenating & Stacking

Combining multiple arrays together:

| Function | Description |
|---|---|
| `np.concatenate([a, b], axis)` | Join along an **existing** axis |
| `np.vstack([a, b])` | Stack **vertically** (add rows) — same as `concatenate` with `axis=0` |
| `np.hstack([a, b])` | Stack **horizontally** (add columns) — same as `concatenate` with `axis=1` |

In [89]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# vstack: add rows (vertical stack)
print("vstack:\n", np.vstack([a, b]))

vstack:
 [[1 2]
 [3 4]
 [5 6]]


In [90]:
# hstack: add columns (horizontal stack)
c = np.array([[5], [6]])
print("hstack:\n", np.hstack([a, c]))

hstack:
 [[1 2 5]
 [3 4 6]]


In [ ]:
# concatenate along axis=0 (rows)
print(np.concatenate([a, np.array([[5, 6]])], axis=0))

## Dot Product (Matrix Multiplication)

- **1D dot product**: `np.dot(x, y)` or `x @ y` → sum of element-wise products: `1×4 + 2×5 + 3×6 = 32`
- **2D dot product**: Matrix multiplication following linear algebra rules — `(m×n) @ (n×p) = (m×p)`

The `@` operator is a shorthand for `np.dot()`.

In [92]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [93]:
print(np.dot(x, y))

32


In [94]:
print(x @ y)

32


In [ ]:
# Manual verification of dot product
print("1*4 + 2*5 + 3*6 =", 1*4 + 2*5 + 3*6)

In [96]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[0, 1], [1, 0]])

In [97]:
print(a)

[[1 2]
 [3 4]]


In [98]:
print(b)

[[0 1]
 [1 0]]


In [ ]:
# 2D dot product (matrix multiplication)
print(np.dot(a, b))

In [100]:
print(np.array([1, 2]) @ np.array([0, 1]))  # 1 * 0 + 2 * 1 = 2

2


In [101]:
print(np.array([1, 2]) @ np.array([1, 0]))

1


In [102]:
print(np.array([3, 4]) @ np.array([0, 1]))

4


In [103]:
print(np.array([3, 4]) @ np.array([1, 0]))

3


## Random Number Generation

NumPy's `random` module generates random numbers:

| Function | Description |
|---|---|
| `np.random.seed(n)` | Set seed for **reproducibility** |
| `np.random.rand(n)` | Random floats in `[0, 1)` — **uniform** distribution |
| `np.random.randn(n)` | Random floats — **normal (Gaussian)** distribution (mean=0, std=1) |
| `np.random.randint(low, high, size)` | Random **integers** in `[low, high)` |
| `np.random.choice(array, n)` | Randomly **pick** n elements from an array |
| `np.random.shuffle(array)` | **Shuffle** the array in place |

In [ ]:
np.random.seed(42)  # Set seed for reproducibility

# rand: random floats between 0 and 1 (uniform distribution)
print("rand(2):", np.random.rand(2))

In [ ]:
# randn: random floats from normal distribution (mean=0, std=1)
print("randn(2):", np.random.randn(2))

In [ ]:
# std of 10000 random normal values ≈ 1.0 (confirms normal distribution)
x = np.random.randn(10000)
print("std:", x.std())

In [ ]:
# randint: random integers in [0, 10) with shape (5, 2)
print(np.random.randint(0, 10, (5, 2)))

In [ ]:
# randint: 3 random integers in [0, 10)
print(np.random.randint(0, 10, 3))

In [ ]:
a = np.arange(10)
print(a)

In [ ]:
# choice: randomly pick 3 elements from the array
print(np.random.choice(a, 3))

In [ ]:
# shuffle: randomly reorder elements in place
np.random.shuffle(a)
print(a)

## Broadcasting

NumPy's mechanism for performing operations on arrays with **different shapes**.

The smaller array is automatically "broadcast" (stretched) to match the larger array.

**Rules:**
1. Arrays with fewer dimensions get padded with 1s on the left
2. Dimensions of size 1 are stretched to match the other array
3. If dimensions don't match and neither is 1, an error is raised

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2, 3)
b = np.array([10, 20, 30])             # shape (3,) → broadcast to (2, 3)

# b is automatically broadcast to match a's shape
print(a + b)

In [ ]:
# Column vector (3,1) + Row vector (1,2) → result (3,2)
col = np.array([[1], [2], [3]])  # shape (3, 1)
row = np.array([10, 20])         # shape (2,)

print(col + row)

## Universal Functions — `where` Parameter

All NumPy ufuncs support the `where` parameter for **conditional computation**.

- `np.where(condition, x, y)` → returns `x` where condition is True, `y` where False
- `np.sqrt(arr, where=mask, out=result)` → only compute where mask is True

In [ ]:
x = np.array([1, -2, 3, -4, 5])

# np.where: replace negatives with 0
print(np.where(x > 0, x, 0))

In [ ]:
# ufunc with where parameter: only compute sqrt where x > 0
result = np.zeros_like(x, dtype=float)
np.sqrt(x, where=(x > 0), out=result)
print(result)

## NumPy vs Python List

Why use NumPy arrays instead of Python lists?

1. **Speed**: NumPy stores data in **contiguous memory** → much faster (C-level optimized)
2. **Vectorized operations**: Direct math on arrays without Python loops
3. **Less memory**: Fixed `dtype` → lower memory usage, ideal for **ML/DL**

In [116]:
import time

# Speed comparison: Python list vs NumPy array
size = 1_000_000
lst = list(range(size))
arr = np.arange(size)

start = time.time()
result_list = [x * 2 for x in lst]
list_time = time.time() - start

start = time.time()
result_arr = arr * 2
numpy_time = time.time() - start

print(f"Python list: {list_time:.4f}s")
print(f"NumPy array: {numpy_time:.4f}s")
print(f"NumPy is ~{list_time / numpy_time:.0f}x faster!")

Python list: 0.0339s
NumPy array: 0.0019s
NumPy is ~17x faster!


In [117]:
# Simpler syntax with NumPy

# Python list: need list comprehension
lst = [1, 2, 3, 4, 5]
result_list = [x ** 2 + 2 * x + 1 for x in lst]
print("List:", result_list)

# NumPy: direct mathematical expression
arr = np.array([1, 2, 3, 4, 5])
result_numpy = arr ** 2 + 2 * arr + 1
print("NumPy:", result_numpy)

List: [4, 9, 16, 25, 36]
NumPy: [ 4  9 16 25 36]


## Linear Algebra (`np.linalg`)

### Vector Norm
Norm measures the **magnitude** (size) of a vector — how far it is from the origin.

- **L1 norm**: sum of absolute values → `|x₁| + |x₂| + ...`
- **L2 norm**: Euclidean distance → `√(x₁² + x₂² + ...)`

In [118]:
v = np.array([3, -4])

print("L1 norm:", np.linalg.norm(v, ord=1))  # |3| + |-4| = 7
print("L2 norm:", np.linalg.norm(v, ord=2))  # √(9 + 16) = 5.0

L1 norm: 7.0
L2 norm: 5.0


### Determinant & Inverse Matrix

- **Determinant**: A scalar value computed from a square matrix. If `det = 0`, the matrix has no inverse.
- **Inverse**: `A⁻¹` such that `A @ A⁻¹ = Identity matrix`

In [119]:
A = np.array([[1, 2], [3, 4]])

# Determinant: 1*4 - 2*3 = -2
print("det(A):", np.linalg.det(A))

det(A): -2.0000000000000004


In [120]:
# Inverse matrix
A_inv = np.linalg.inv(A)
print("A inverse:\n", A_inv)

# Verify: A @ A_inv ≈ Identity
print("\nA @ A_inv:\n", np.round(A @ A_inv))

A inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]

A @ A_inv:
 [[1. 0.]
 [0. 1.]]


### Eigenvalues & Eigenvectors

When a matrix is applied to a special vector (**eigenvector**), it only **scales** the vector — doesn't change its direction. The scaling factor is the **eigenvalue**.

`A @ v = λ × v` where `v` = eigenvector, `λ` = eigenvalue

In [121]:
A = np.array([[2, 1], [1, 2]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
# Verify: A @ eigenvector = eigenvalue * eigenvector
v = eigenvectors[:, 0]  # type: ignore # first eigenvector
lam = eigenvalues[0]    # first eigenvalue

print("A @ v   =", A @ v)
print("λ × v   =", lam * v)
print("Equal?", np.allclose(A @ v, lam * v))

A @ v   = [2.12132034 2.12132034]
λ × v   = [2.12132034 2.12132034]
Equal? True
