In [16]:
import torch

tensor = torch.tensor([[2, 3, 4 ,5],
                       [6, 7, 8,9]])   # 2x4 tensor
print(tensor.shape)  # Output: torch.Size([2, 4])

torch.Size([2, 4])


In [18]:
tensor

tensor([[2, 3, 4, 5],
        [6, 7, 8, 9]])

In [19]:
tensor_T = tensor.T      # tensor transpose (ترانهاده تنسور)
print(tensor_T.shape)  # Output: torch.Size([4, 2])
tensor_T

torch.Size([4, 2])


tensor([[2, 6],
        [3, 7],
        [4, 8],
        [5, 9]])

## 2. Matrix multiplication vs element-wise (ضرب ماتریسی در مقابل ضرب نظیر به نظیر)

### 2.1 Matrix multiplication (ضرب ماتریسی)

In [21]:
y1=torch.matmul(tensor, tensor_T)  # (matrix multiplication)
y1

tensor([[ 54, 110],
        [110, 230]])

These two results are the same.
@ (the @ sign) is just a shortcut for torch.matmul.

In [23]:
y2=tensor @ tensor_T  # (matrix multiplication) Using the operator@
y2

tensor([[ 54, 110],
        [110, 230]])

## 2.2 Random tensor with same shape (تنسور تصادفی هم‌شکل)

In [25]:
y3 = torch.rand_like(tensor, dtype=torch.float32)    # Create a tensor with the same shape as 'tensor' filled with random values
y3

tensor([[0.3702, 0.3404, 0.1886, 0.5177],
        [0.7401, 0.9807, 0.5048, 0.8257]])

## 2.3 Element-wise multiplication (ضرب نظیر به نظیر)

In [27]:
ew = tensor * tensor            # element-wise multiplication (ضرب عضو به عضو)
ew

tensor([[ 4,  9, 16, 25],
        [36, 49, 64, 81]])

In [29]:
print("\new = tensor * tensor")
print(ew)


ew = tensor * tensor
tensor([[ 4,  9, 16, 25],
        [36, 49, 64, 81]])


In [30]:
mm = tensor @ tensor.T
print(mm)

tensor([[ 54, 110],
        [110, 230]])


In [31]:
import torch

tensor = torch.tensor([
    [2, 3, 4, 5],
    [6, 7, 8, 9]
])

ew = tensor * tensor

# shape  - number of rows and columns
rows = tensor.shape[0]
cols = tensor.shape[1]

print("Element-wise multiplication details:\n")

for i in range(rows):
    for j in range(cols):
        a = tensor[i, j]      # current element 
        b = tensor[i, j]      # same element again 
        c = ew[i, j]          # result of multiplication 
        print(f"tensor[{i},{j}] * tensor[{i},{j}] = {a} * {b} = {c}")

Element-wise multiplication details:

tensor[0,0] * tensor[0,0] = 2 * 2 = 4
tensor[0,1] * tensor[0,1] = 3 * 3 = 9
tensor[0,2] * tensor[0,2] = 4 * 4 = 16
tensor[0,3] * tensor[0,3] = 5 * 5 = 25
tensor[1,0] * tensor[1,0] = 6 * 6 = 36
tensor[1,1] * tensor[1,1] = 7 * 7 = 49
tensor[1,2] * tensor[1,2] = 8 * 8 = 64
tensor[1,3] * tensor[1,3] = 9 * 9 = 81


In [36]:
rows = tensor.shape[0]
cols = tensor.shape[1]
print(f"\nTensor shape: {tensor.shape} (rows: {rows}, columns: {cols})")


Tensor shape: torch.Size([2, 4]) (rows: 2, columns: 4)


In [37]:
tensor = torch.tensor([
    [2, 3, 4, 5],
    [6, 7, 8, 9]
])

In [35]:
print(tensor.shape) # Output: torch.Size([2, 4])

torch.Size([2, 4])


This means:

2 = rows
, 4 = columns

So the tensor has shape (2, 4).

## 3. Aggregation and .sum() (تجمع و جمع)

Aggregation (تجمع) یعنی چند عدد را در یک مقدار خلاصه کنیم (summarize many numbers into one).

In [38]:
x= torch.tensor([[2, 3, 4 ,5],
                 [6, 7, 8,9]]) 
x

tensor([[2, 3, 4, 5],
        [6, 7, 8, 9]])

In [41]:
s=x.sum()
print("Sum tensor :",s)
print("Type of s :", type(s))

Sum tensor : tensor(44)
Type of s : <class 'torch.Tensor'>


## 4. .item() for single-element tensor

If the tensor has only one value, we can convert it to a Python number.

In [42]:
value = s.item()
print("Scalar value of s:", value)
print("Type of value:", type(value))

Scalar value of s: 44
Type of value: <class 'int'>


## 5. In-place operations with underscore _ (اعمال درجا با زیرخط)

In-place operation means that the original variable itself is changed (no new tensor).

In [43]:
tensor = torch.tensor([1, 0, 1, 1, 1, 0, 1, 1])
print("Original tensor :", tensor)

tensor.add_(5)

Original tensor : tensor([1, 0, 1, 1, 1, 0, 1, 1])
Tensor after in-place addition: tensor([6, 5, 6, 6, 6, 5, 6, 6])


 1) Add 5 to each element of the tensor.
 2) Store the result in the same tensor (in-place operation).

 before : [1, 0, 1, 1, 1, 0, 1, 1]
 
 after:  [6, 5, 6, 6, 6, 5, 6, 6]

In [44]:
print("Tensor after in-place addition:", tensor)

Tensor after in-place addition: tensor([6, 5, 6, 6, 6, 5, 6, 6])


## 6. Tensor <-> NumPy and Shared Memory

### 6.1 Tensor -> NumPy

For a CPU tensor, `tensor.numpy()` usually returns a NumPy array that shares the same underlying memory.

Note:
- This section assumes CPU tensors.
- For GPU tensors, move to CPU first (for example, `tensor.cpu().numpy()`).

In [46]:
# Create a 1D tensor of ones

t = torch.ones(5)

# t – tensor with shape (5,) and values ​​[1., 1., 1., 1., 1.]

# Convert to NumPy array

n = t.numpy()

# n – NumPy array.
# Note: t and n share memory.

print("Tensor t:", t)
print("NumPy n:", n)

Tensor t: tensor([1., 1., 1., 1., 1.])
NumPy n: [1. 1. 1. 1. 1.]


### 6.2 In-place Update on Tensor Affects NumPy (when memory is shared)

If `n = t.numpy()` shares memory with `t`, then an in-place update on `t` (such as `t.add_(1)`) is visible in `n` as well.

In [48]:
t.add_(1) # add 1 in-place
print("Tensor t after add_:", t)
print("NumPy n after tensor change:", n)
# Since t and n share memory, the change in t is also visible to n.

Tensor t after add_: tensor([3., 3., 3., 3., 3.])
NumPy n after tensor change: [3. 3. 3. 3. 3.]


### 6.3 NumPy -> Tensor and In-place Update on NumPy

`torch.from_numpy(n2)` creates a tensor that shares memory with `n2`.

Therefore, in-place updates on `n2` are reflected in `t2`, and vice versa.

In [49]:
import numpy as np

# Create NumPy array
n2 = np.ones(5)
print("Original NumPy n2:", n2)

# From NumPy to tensor
t2 = torch.from_numpy(n2)
# t2 – is a tensor created from n2 and has shared memory.

print("Tensor t2:", t2)

# In-place add on NumPy array
np.add(n2, 1, out=n2)
# np.add(a, b, out=a) – adds b to each element of a and writes the result to out (a itself).
# Here: all elements of n2 are incremented by one.

print("NumPy n2 after np.add:", n2)
print("Tensor t2 after np.add on n2:", t2)
# Since t2 and n2 share memory, t2 has also changed.

Original NumPy n2: [1. 1. 1. 1. 1.]
Tensor t2: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
NumPy n2 after np.add: [2. 2. 2. 2. 2.]
Tensor t2 after np.add on n2: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
