## 1- Explanation of Tensor

- Tensor = n-D array ((Multidimensional array)).

A **tensor** is a multi-dimensional array used in PyTorch to store and process data.

- Scalar: 0D tensor
- Vector: 1D tensor
- Matrix: 2D tensor
- Higher dimensions: 3D+ tensors

Tensors can run on CPU or GPU and support automatic differentiation for deep learning.

In [1]:
import torch

tensor = torch.tensor([[2, 3, 4 ,5],
                       [6, 7, 8,9]])   # 2x4 tensor
print(tensor.shape)  # Output: torch.Size([2, 4])

torch.Size([2, 4])


In [18]:
tensor

tensor([[2, 3, 4, 5],
        [6, 7, 8, 9]])

### Transpose Example (`.T`)

>> We have a tensor of shape `(2, 4)`. Using `.T`, the rows and columns are swapped and the shape becomes `(4, 2)`.

```python
tensor_T = tensor.T
print(tensor_T.shape)  # torch.Size([4, 2])
tensor_T
```

A 2x4 PyTorch tensor containing integer values and initialized with the nested list `[[2, 3, 4, 5], [6, 7, 8, 9]]`.
The `.T` attribute is used to compute the transpose of the tensor, which results in a new tensor with dimensions swapped.
In this case, the original tensor has a shape of `(2, 4)`, and after transposition, it has a shape of `(4, 2)`.
The output of `print(tensor_T.shape)` confirms this by displaying `torch.Size([4, 2])`.

In [ ]:
tensor_T = tensor.T      # tensor transpose 
print(tensor_T.shape)    # Output: torch.Size([4, 2])
tensor_T

torch.Size([4, 2])


tensor([[2, 6],
        [3, 7],
        [4, 8],
        [5, 9]])

## 2. Matrix multiplication vs element-wise .
- `.T` = transpose (ترانهاده).
- `@` یا `torch.matmul` = matrix multiplication (ضرب ماتریسی).
- `*` = element-wise multiplication (ضرب نظیر به نظیر).

### 2.1 Matrix multiplication (ضرب ماتریسی)

In [21]:
y1=torch.matmul(tensor, tensor_T)  # (matrix multiplication)
y1

tensor([[ 54, 110],
        [110, 230]])

These two results are the same.
@ (the @ sign) is just a shortcut for torch.matmul.

In [23]:
y2=tensor @ tensor_T  # (matrix multiplication) Using the operator@
y2

tensor([[ 54, 110],
        [110, 230]])

## 2.2 Random tensor with same shape .

In [25]:
y3 = torch.rand_like(tensor, dtype=torch.float32)    # Create a tensor with the same shape as 'tensor' filled with random values
y3

tensor([[0.3702, 0.3404, 0.1886, 0.5177],
        [0.7401, 0.9807, 0.5048, 0.8257]])

## 2.3 Element-wise multiplication (ضرب نظیر به نظیر)

In [ ]:
ew = tensor * tensor                    # element-wise multiplication (ضرب عضو به عضو)
ew

tensor([[ 4,  9, 16, 25],
        [36, 49, 64, 81]])

In [ ]:
print("\n ew = tensor * tensor")         # element-wise multiplication (ضرب عضو به عضو)
print(ew)


ew = tensor * tensor
tensor([[ 4,  9, 16, 25],
        [36, 49, 64, 81]])


In [ ]:
mm = tensor @ tensor.T             
      # matrix multiplication (ضرب ماتریسی)
print(mm)                                # نمایش نتیجه ضرب ماتریسی

tensor([[ 54, 110],
        [110, 230]])


In [2]:
import torch

tensor = torch.tensor([                
    [2, 3, 4, 5],
    [6, 7, 8, 9]
])

ew = tensor * tensor

# shape  - number of rows and columns
rows = tensor.shape[0]           # number of rows
cols = tensor.shape[1]           # number of columns

print("Element-wise multiplication details:\n")

for i in range(rows):
    for j in range(cols):
        a = tensor[i, j]      # current element 
        b = tensor[i, j]      # same element again 
        c = ew[i, j]          # result of multiplication 
        
        print(f"tensor[{i},{j}] * tensor[{i},{j}] = {a} * {b} = {c}")

Element-wise multiplication details:

tensor[0,0] * tensor[0,0] = 2 * 2 = 4
tensor[0,1] * tensor[0,1] = 3 * 3 = 9
tensor[0,2] * tensor[0,2] = 4 * 4 = 16
tensor[0,3] * tensor[0,3] = 5 * 5 = 25
tensor[1,0] * tensor[1,0] = 6 * 6 = 36
tensor[1,1] * tensor[1,1] = 7 * 7 = 49
tensor[1,2] * tensor[1,2] = 8 * 8 = 64
tensor[1,3] * tensor[1,3] = 9 * 9 = 81


In [36]:
rows = tensor.shape[0]
cols = tensor.shape[1]
print(f"\nTensor shape: {tensor.shape} (rows: {rows}, columns: {cols})")


Tensor shape: torch.Size([2, 4]) (rows: 2, columns: 4)


In [4]:
tensor = torch.tensor([
    [2, 3, 4, 5],
    [6, 7, 8, 9]
])
tensor 

tensor([[2, 3, 4, 5],
        [6, 7, 8, 9]])

In [6]:
tensor.T

tensor([[2, 6],
        [3, 7],
        [4, 8],
        [5, 9]])

In [35]:
print(tensor.shape) # Output: torch.Size([2, 4])

torch.Size([2, 4])


This means:

2 = rows
, 4 = columns

So the tensor has shape (2, 4).

## 3. Aggregation and .sum() (تجمع و جمع)

- `.sum()` = aggregation (تجمع) روی همهٔ عناصر.

Aggregation (تجمع) یعنی چند عدد را در یک مقدار خلاصه کنیم (summarize many numbers into one).

In [38]:
x= torch.tensor([[2, 3, 4 ,5],
                 [6, 7, 8,9]]) 
x

tensor([[2, 3, 4, 5],
        [6, 7, 8, 9]])

In [41]:
s=x.sum()
print("Sum tensor :",s)
print("Type of s :", type(s))

Sum tensor : tensor(44)
Type of s : <class 'torch.Tensor'>


## 4. .item() for single-element tensor
- `.item()` = Convert a single-element tensor to a Python number.

If the tensor has only one value, we can convert it to a Python number.

In [24]:
x=torch.tensor([[1, 2, 3, 4], [6, 7, 8, 9]])
s = x.sum()                          # Create a single-element tensor (sum of all elements)
value = s.item()                     # Convert the single-element tensor to a Python scalar
print("Scalar value of s:", value)   # Displaying the scalar value resulting from the sum of tensor elements
print("Type of value:", type(value)) # Displaying the type of the scalar value
print("\n=== s ===" ,s)


Scalar value of s: 40
Type of value: <class 'int'>

=== s === tensor(40)


## 5. In-place operations with underscore .

- Functions with `_` (like `add_`) = in-place (change on the same variable).

In-place operation means that the original variable itself is changed (no new tensor).

In [28]:
tensor = torch.tensor([1, 0, 1, 1, 1, 0, 1, 1])
print("Original tensor :", tensor)

Original tensor : tensor([1, 0, 1, 1, 1, 0, 1, 1])


 1) Add 5 to each element of the tensor.
 2) Store the result in the same tensor (in-place operation).

 before : [1, 0, 1, 1, 1, 0, 1, 1]
 
 after:  [6, 5, 6, 6, 6, 5, 6, 6]

In [31]:
tensor = torch.tensor([1, 0, 1, 1, 1, 0, 1, 1])

tensor.add_(5)

print(tensor)

tensor([6, 5, 6, 6, 6, 5, 6, 6])


🧠 Key rule

add_() → changes original tensor (in-place)

add() → creates new tensor (no change to original)

In [32]:
print("Tensor after in-place addition:", tensor)

Tensor after in-place addition: tensor([6, 5, 6, 6, 6, 5, 6, 6])


## 6. Tensor <-> NumPy and Shared Memory

PyTorch tensors and NumPy arrays can be converted into each other:

- `tensor.numpy()` -> Tensor -> NumPy
- `torch.from_numpy()` -> NumPy -> Tensor

---

## Key Idea: Shared Memory

Sometimes, both objects share the same memory.

This means:
- They point to the same underlying data
- Changing one can also change the other

---

## 6.1 Tensor -> NumPy

```python
import torch

t = torch.tensor([1, 2, 3])
a = t.numpy()

print("Tensor:", t)
print("NumPy array:", a)
```

### What happens?

- `t` = PyTorch tensor
- `a` = NumPy array
- They share memory

---

### In-place change (standalone runnable)

```python
import torch

t = torch.tensor([1, 2, 3])
a = t.numpy()
a[0] = 99

print("Tensor:", t)
print("NumPy:", a)
```

Both change, because both refer to the same memory.

---

## Important Rule

This works only if:

- Tensor is on CPU
- No `.copy()` is used

---

## 6.2 Tensor Change -> NumPy Changes

```python
import torch

t = torch.ones(5)
n = t.numpy()

print("Before change")
print("Tensor t:", t)
print("NumPy n:", n)

t.add_(1)   # in-place operation

print("\nAfter in-place change")
print("Tensor t:", t)
print("NumPy n:", n)
```

NumPy also changes.

---

### Why?

- `add_()` is in-place
- Memory is shared

---

## 6.3 NumPy -> Tensor

```python
import torch
import numpy as np

n2 = np.ones(5)
t2 = torch.from_numpy(n2)

print("Before change")
print("NumPy n2:", n2)
print("Tensor t2:", t2)

np.add(n2, 1, out=n2)  # in-place on NumPy

print("\nAfter in-place NumPy change")
print("NumPy n2:", n2)
print("Tensor t2:", t2)
```

Tensor also changes.

---

## Summary Table

| Operation              | Shared Memory |
| ---------------------- | ------------- |
| `tensor.numpy()` (CPU) | Yes           |
| `torch.from_numpy()`   | Yes           |
| `.copy()` used         | No            |
| GPU tensor             | No            |

---

## Interview Answer

A PyTorch tensor and a NumPy array can share the same underlying memory when converted using `.numpy()` or `torch.from_numpy()`.
This means in-place changes in one can be reflected in the other, as long as the tensor is on CPU and no copy is made.

---

## Simple Mental Model

```
Tensor ---+
          +--- same memory
NumPy  ---+
```

---

## Important Tip

If you do not want shared behavior:

```python
import torch

t = torch.tensor([1, 2, 3])
a = t.numpy().copy()  # independent memory
```

---

## 7. In-place vs Out-of-place Operations

### Key Idea

- In-place operation -> changes the same memory
- Out-of-place operation -> creates new memory

---

## In-place Operation

In PyTorch, functions ending with `_` are in-place.

```python
import torch

t = torch.tensor([1, 2, 3])
t.add_(1)

print(t)
```

### What happened?

- `add_()` modified `t` directly
- No new tensor was created

---

## Out-of-place Operation

```python
import torch

t = torch.tensor([1, 2, 3])
t2 = t.add(1)

print("t:", t)    # original unchanged
print("t2:", t2)  # new tensor
```

### What happened?

- `t` stays the same
- `t2` is a new tensor

---

## Why is this important?

Because of shared memory.

---

## Example with NumPy (in-place)

```python
import torch

t = torch.tensor([1, 2, 3])
a = t.numpy()

t.add_(1)   # in-place

print("t:", t)
print("a:", a)
```

Now both change:

- `t` changes
- `a` also changes

---

## But with out-of-place

```python
import torch

t = torch.tensor([1, 2, 3])
a = t.numpy()

t = t.add(1)   # new tensor

print("t:", t)
print("a:", a)
```

Now:

- `t` changes
- `a` stays old

---

## Mental Model

### In-place

```
same memory -> changed
```

### Out-of-place

```
old memory -> stays
new memory -> created
```

---

## Interview Answer

In PyTorch, in-place operations (like `add_()`) modify the tensor memory directly, while out-of-place operations (like `add()`) create a new tensor.
This is important when tensors share memory with NumPy arrays, because in-place changes can affect both.

---

## Quick Check

If you write:

```python
import torch

t = torch.tensor([1, 2, 3])
a = t.numpy()

t = t.add(1)
print("t:", t)
print("a:", a)
```

Answer: `a` does not change, because `t = t.add(1)` creates a new tensor instead of modifying the old shared memory.

In [ ]:
import torch
import numpy as np

print("=== Quick runnable check: Tensor <-> NumPy shared memory ===")
t = torch.tensor([1, 2, 3])
a = t.numpy()
print("Before:", "t=", t, "a=", a)

a[0] = 99  # in-place on NumPy
print("After NumPy in-place:", "t=", t, "a=", a)

print("\n=== In-place vs Out-of-place ===")
t = torch.tensor([1, 2, 3])
a = t.numpy()

t.add_(1)  # in-place on tensor
print("After t.add_(1):", "t=", t, "a=", a)

t = t.add(1)  # out-of-place (new tensor)
print("After t = t.add(1):", "t=", t, "a=", a)

print("\n=== NumPy -> Tensor shared memory ===")
n2 = np.ones(5) #np.ones(shape) creates a NumPy array filled with 1s
t2 = torch.from_numpy(n2)
print("Before:", "n2=", n2, "t2=", t2)

np.add(n2, 1, out=n2)  # in-place on NumPy
print("After np.add(..., out=n2):", "n2=", n2, "t2=", t2)

=== Quick runnable check: Tensor <-> NumPy shared memory ===
Before: t= tensor([1, 2, 3]) a= [1 2 3]
After NumPy in-place: t= tensor([99,  2,  3]) a= [99  2  3]

=== In-place vs Out-of-place ===
After t.add_(1): t= tensor([2, 3, 4]) a= [2 3 4]
After t = t.add(1): t= tensor([3, 4, 5]) a= [2 3 4]

=== NumPy -> Tensor shared memory ===
Before: n2= [1. 1. 1. 1. 1.] t2= tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
After np.add(..., out=n2): n2= [2. 2. 2. 2. 2.] t2= tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


````
## 🔹 What is `np.ones`?

```python
n2 = np.ones(5)
````
### Meaning:

* `np.ones(shape)` creates a NumPy array filled with **1s**

### In your case:

```python
np.ones(5)
```
👉 creates:
```text
[1. 1. 1. 1. 1.]
```
* length = 5
* values = all ones
* type = NumPy array


## Step 1 — Step-by-step meaning

- `n2` → your array  
- `1` → value to add  
- `out=n2` → store result back in **same array**

---

## Step 2 — Simple interpretation

👉 “Add 1 to every element of n2 and write the result into n2 itself”

---

## Step 3 — Example

Before:

```text
n2 = [1. 1. 1. 1. 1.]
````

After:

```text
n2 = [2. 2. 2. 2. 2.]
```

---

## Step 4 — Very important concept

This is an **in-place operation**

* It does NOT create a new array
* It modifies the same memory

---

## Step 5 — Why does `t2` also change?

```python
t2 = torch.from_numpy(n2)
```

👉 `t2` shares memory with `n2`

---

## Step 6 — Apply operation

```python
np.add(n2, 1, out=n2)
```

---

## Step 7 — Result

```text
n2 → updated
t2 → also updated
```

---

## Step 8 — Mental model

```text
n2  ───┐
       ├── same memory
t2  ───┘
```

---

## Step 9 — Equivalent simpler version

```python
n2 += 1
```

👉 also in-place

---

## Step 10 — Important correction

```python
n3 = np.add(n2, 1)
```

👉 This is **NOT in-place**

---

## Step 11 — What happens here?

* A **new array** is created
* Stored in `n3`
* `n2` stays unchanged

---

## Step 12 — Memory situation

```text
n2  ─── original memory
t2  ─── same memory as n2

n3  ─── NEW memory
```

---

## Step 13 — Compare

### ✔ In-place

```python
np.add(n2, 1, out=n2)
```

👉 changes `n2` → `t2` also changes

---

### ❌ Not in-place

```python
n3 = np.add(n2, 1)
```

👉 new array → `t2` does NOT change

---

## Step 14 — Simple rule

* with `out=` → in-place → shared change
* without `out=` → new array → no shared change

---

## Step 15 — Interview sentence

`np.add(n2, 1, out=n2)` is an in-place operation that modifies the original array, while `np.add(n2, 1)` creates a new array. Only in-place operations affect shared memory with PyTorch tensors.

```
```

